export const POST_ADMIN_REQUEST = "POST_ADMIN_REQUEST";
export const POST_ADMIN_SUCCESS = "POST_ADMIN_SUCCESS";
export const POST_ADMIN_FAILURE = "POST_ADMIN_FAILURE";

export const GET_ADMIN_REQUEST = "GET_ADMIN_REQUEST";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const GET_ADMIN_FAILURE = "GET_ADMIN_FAILURE";


export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";

